
import 'package:riverpod_annotation/riverpod_annotation.dart';
part 'current_question_provider.g.dart';

/// A Riverpod state provider for managing the current question number.
///
/// The [CurrentQuestionP] class extends from a generated provider class (likely generated by Riverpod).
/// It is responsible for keeping track of and updating the current question number.
@riverpod
class CurrentQuestionP extends _$CurrentQuestionP {
  /// Initializes the current question number to 0.
  @override
  int build() {
    return 0;
  }

  /// Changes the current question number to the specified [questionNo].
  void changeCurrentQuestion(int questionNo) {
    state = questionNo;
  }

  /// Decrements the current question number by 1 and returns the updated value.
  ///
  /// If the current question number is already 0, it returns 0 without decrementing.
  int backCurrentQuestionNo() {
    if (state <= 0) return 0;
    state = state - 1;
    return state;
  }

  /// Increments the current question number by 1 and returns the updated value.
  int nextQuestionNo() {
    state += 1;
    return state;
  }
}
