// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'current_question_provider.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

String _$currentQuestionPHash() => r'7f2e582bc20d1552aabfbddfdb41434256b847c2';

/// A Riverpod state provider for managing the current question number.
///
/// The [CurrentQuestionP] class extends from a generated provider class (likely generated by Riverpod).
/// It is responsible for keeping track of and updating the current question number.
///
/// Copied from [CurrentQuestionP].
@ProviderFor(CurrentQuestionP)
final currentQuestionPProvider =
    AutoDisposeNotifierProvider<CurrentQuestionP, int>.internal(
  CurrentQuestionP.new,
  name: r'currentQuestionPProvider',
  debugGetCreateSourceHash: const bool.fromEnvironment('dart.vm.product')
      ? null
      : _$currentQuestionPHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef _$CurrentQuestionP = AutoDisposeNotifier<int>;
// ignore_for_file: type=lint
// ignore_for_file: subtype_of_sealed_class, invalid_use_of_internal_member, invalid_use_of_visible_for_testing_member
