// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'get_total_question_count_provider.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

String _$getTotalQuestionCountPHash() =>
    r'22d8f5e027cf75c410ada8234623017788c06c39';

/// A Riverpod state provider for fetching and managing the total question count.
///
/// The [GetTotalQuestionCountP] class extends from a generated provider class (likely generated by Riverpod).
/// It is responsible for fetching and managing the total number of questions in a database.
///
/// Copied from [GetTotalQuestionCountP].
@ProviderFor(GetTotalQuestionCountP)
final getTotalQuestionCountPProvider =
    AsyncNotifierProvider<GetTotalQuestionCountP, int>.internal(
  GetTotalQuestionCountP.new,
  name: r'getTotalQuestionCountPProvider',
  debugGetCreateSourceHash: const bool.fromEnvironment('dart.vm.product')
      ? null
      : _$getTotalQuestionCountPHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef _$GetTotalQuestionCountP = AsyncNotifier<int>;
// ignore_for_file: type=lint
// ignore_for_file: subtype_of_sealed_class, invalid_use_of_internal_member, invalid_use_of_visible_for_testing_member
