// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'get_question_provider.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

String _$getQuestionPHash() => r'9c1bed7e453f4f641dde2629528c69091e205195';

/// A Riverpod state provider for fetching and managing questions.
///
/// The [GetQuestionP] class extends from a generated provider class (likely generated by Riverpod).
/// It is responsible for fetching and managing questions based on subject and question ID.
///
/// Copied from [GetQuestionP].
@ProviderFor(GetQuestionP)
final getQuestionPProvider =
    AutoDisposeAsyncNotifierProvider<GetQuestionP, QuestionModel?>.internal(
  GetQuestionP.new,
  name: r'getQuestionPProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$getQuestionPHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef _$GetQuestionP = AutoDisposeAsyncNotifier<QuestionModel?>;
// ignore_for_file: type=lint
// ignore_for_file: subtype_of_sealed_class, invalid_use_of_internal_member, invalid_use_of_visible_for_testing_member
